# Generated by Django 4.1.7 on 2023-03-11 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=100, verbose_name='Наименование товара')),
                ('category', models.CharField(max_length=100, verbose_name='Категория')),
                ('product_description', models.CharField(max_length=100, verbose_name='Описание товара')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена')),
                ('quantity_stock', models.PositiveIntegerField(verbose_name='Количество на складе')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продкуты',
                'ordering': ['-time_create', 'product_title'],
            },
        ),
    ]
